server:
  port: 88
spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.85.1:8848
    gateway:
      routes:
        - id: gulimall-product  #商品服务
          uri: lb://gulimall-product # 路由给gulimall-product，lb代表负载均衡
          predicates: # 什么情况下路由给它
            - Path=/api/product/**,/hello # 路径匹配规则
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment} # 过滤器：过滤掉url里的manager,例如http://ip:port/manager/test -> http://ip:port/test
        - id: gulimall-member  #会员服务
          uri: lb://gulimall-member # 路由给gulimall-member，lb代表负载均衡
          predicates: # 什么情况下路由给它
            - Path=/api/member/** # 路径匹配规则
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment} # 过滤器：过滤掉url里的manager,例如http://ip:port/manager/test -> http://ip:port/test
        - id: third_party_route  #第三方集成服务
          uri: lb://third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*), /$\{segment}
        - id: gulimall-ware  #会员服务
          uri: lb://gulimall-ware # 路由给gulimall-ware，lb代表负载均衡
          predicates: # 什么情况下路由给它
            - Path=/api/ware/** # 路径匹配规则
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment} # 过滤器：过滤掉url里的manager,例如http://ip:port/manager/test -> http://ip:port/test
        - id: renren-fast #后台管理服务
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}
        - id: mall_host_toute
          uri: lb://gulimall-product #目标服务
          predicates:
            - Host=gulimall.com,item.gulimall.com #监听的域名
        - id: mall_search_toutec  #搜索服务路由
          uri: lb://gulimall-search #目标服务
          predicates:
            - Host=search.gulimall.com #监听的域名
        - id: mall_auth_toute #认证服务路由
          uri: lb://gulimall-auth-server #目标服务
          predicates:
            - Host=auth.gulimall.com #监听的域名
        - id: gulimall_cart_toute #购物车服务
          uri: lb://gulimall-cart #目标服务
          predicates:
            - Host=cart.gulimall.com #监听的域名
        - id: gulimall_order_toute #订单服务
          uri: lb://gulimall-order #目标服务
          predicates:
            - Host=order.gulimall.com #监听的域名
        - id: gulimall_member_toute #订单服务
          uri: lb://gulimall-member #目标服务
          predicates:
            - Host=member.gulimall.com #监听的域名