server:
  port: 30000
spring:
  application:
    name: third-party
  cloud:
    alicloud:
      accessKey: LTAI5tDNedcF1SLniFt4jbGm
      secretKey: PJZRjsn9DENhMAzNmxSS0vCDgcgd26
      oss:
        endpoint: oss-cn-nanjing.aliyuncs.com
        bucket: gulimall-blsz #自定义配置
      sms:
        host: https://gyytz.market.alicloudapi.com
        path: /sms/smsSend
        app-code: 9e4d0fb3b34a4dedbca01bf98b86ad28
        sms-sign-id: 2e65b1bb3d054466b82f0c9d125465e2
        template-id: 908e94ccf08b4476ba6c876d13f084ad
    nacos:
      discovery:
        server-addr: 192.168.85.1:8848
